"""empty message

Revision ID: 23fd91463a60
Revises: c0d4d6bebcb0
Create Date: 2023-07-26 14:05:12.020080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23fd91463a60'
down_revision = 'c0d4d6bebcb0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
